//go:build generate
// +build generate

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sentrie-sh/sentrie/constraints"
)

//go:generate go run gen.go

func main() {
	// Collect name->numArgs maps from canonical definitions in constraints package
	sections := []struct {
		varName string
		source  map[string]any
	}{
		{"genIntConstraints", toAnyMap(constraints.IntContraintCheckers)},
		{"genFloatConstraints", toAnyMap(constraints.FloatContraintCheckers)},
		{"genStringConstraints", toAnyMap(constraints.StringContraintCheckers)},
		{"genBoolConstraints", toAnyMap(constraints.BoolConstraintCheckers)},
		{"genListConstraints", toAnyMap(constraints.ListContraintCheckers)},
		{"genMapConstraints", toAnyMap(constraints.MapContraintCheckers)},
		{"genDocumentConstraints", toAnyMap(constraints.DocumentContraintCheckers)},
		{"genRecordConstraints", toAnyMap(constraints.RecordContraintCheckers)},
		{"genShapeConstraints", toAnyMap(constraints.ShapeContraintCheckers)},
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString("// This file is generated from canonical constraint definitions in package constraints.\n\n")
	buf.WriteString("package ast\n\n")

	for _, sec := range sections {
		writeMap(&buf, sec.varName, sec.source)
	}

	outPath := filepath.Join(".", "typeref_constraint_args_gen.go")
	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		panic(err)
	}
}

// toAnyMap converts a typed map[name]ConstraintDefinition[T] to a generic map[name]any with NumArgs extracted.
func toAnyMap[T any](src map[string]constraints.ConstraintDefinition[T]) map[string]any {
	res := make(map[string]any, len(src))
	for name, def := range src {
		res[name] = def.NumArgs
	}
	return res
}

func writeMap(buf *bytes.Buffer, varName string, src map[string]any) {
	// Stable order for reproducible diffs
	keys := make([]string, 0, len(src))
	for k := range src {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	buf.WriteString(fmt.Sprintf("var %s = func() map[string]int {\n", varName))
	buf.WriteString("\treturn map[string]int{\n")
	for _, k := range keys {
		v := src[k]
		buf.WriteString("\t\t")
		buf.WriteString(strconvQuote(k))
		buf.WriteString(": ")
		buf.WriteString(fmt.Sprintf("%d", v.(int)))
		buf.WriteString(",\n")
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}()\n\n")
}

func strconvQuote(s string) string {
	// minimal quoting for Go string literal
	return "\"" + strings.ReplaceAll(s, "\"", "\\\"") + "\""
}
