// Copyright 2025 Binaek Sarkar
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by go generate; DO NOT EDIT.
// This file is generated from canonical definitions in `constraints` package.
//
// To update definitions, update the `constraints` package and run `go generate`.

package ast

var genNumberConstraints = map[string]int{
	"eq":           1,
	"even":         0,
	"finite":       0,
	"gt":           1,
	"in":           1,
	"infinite":     0,
	"lt":           1,
	"max":          1,
	"min":          1,
	"multiple_of":  1,
	"nan":          0,
	"negative":     0,
	"neq":          1,
	"non_negative": 0,
	"non_positive": 0,
	"not_in":       1,
	"odd":          0,
	"positive":     0,
	"range":        2,
}

var genStringConstraints = map[string]int{
	"alpha":             0,
	"alphanumeric":      0,
	"email":             0,
	"ends_with":         1,
	"has_substring":     1,
	"length":            1,
	"lowercase":         0,
	"maxlength":         1,
	"minlength":         1,
	"not_empty":         0,
	"not_has_substring": 1,
	"not_one_of":        -1,
	"numeric":           0,
	"one_of":            -1,
	"regexp":            1,
	"starts_with":       1,
	"trimmed":           0,
	"uppercase":         0,
	"url":               0,
	"uuid":              0,
}

var genBoolConstraints = map[string]int{
	"eq":          1,
	"is_false":    0,
	"is_true":     0,
	"neq":         1,
	"not_unknown": 0,
}

var genListConstraints = map[string]int{
	"not_empty": 0,
}

var genMapConstraints = map[string]int{}

var genDocumentConstraints = map[string]int{}

var genRecordConstraints = map[string]int{}

var genShapeConstraints = map[string]int{}
