package ast

// This is a stub file to satisfy the build constraints.
// The actual file is generated by the gen.go script.
var genBoolConstraints = map[string]int{}
var genFloatConstraints = map[string]int{}
var genIntConstraints = map[string]int{}
var genStringConstraints = map[string]int{}
var genListConstraints = map[string]int{}
var genMapConstraints = map[string]int{}
var genRecordConstraints = map[string]int{}
var genShapeConstraints = map[string]int{}
var genDocumentConstraints = map[string]int{}
